### ISSUE TITLE
Bif as input file

### ISSUE THREAD

**Issue by sonujose123** [sysbio-vo/bnfinder#1]
Is there any way to input file format in bif or any online conversion tool available for converting bif to your input file format. (input1.txt)?

**Comment by alnf** [comment]
Let me clarify what do you mean exactly.

[https://github.com/sysbio-vo/bnfinder/blob/master/doc/data/input1.txt](https://github.com/sysbio-vo/bnfinder/blob/master/doc/data/input1.txt) is a simple tab separated value format with one exception - first line. In first line you can pass different parameters, the description of which you can read in doc file (compile from latex in doc folder or use a little bit older version here - http://bioputer.mimuw.edu.pl/software/bnf/bnfinder_doc.pdf).

"#regulators P1 P2" denotes that nodes P1 and P2 are outbounding, which is a crucial part of algorithm as structural constraints forcing network’s acyclicity are necessery for learning a **static** Bayesian network with BNfinder (again, check the doc).

The rest of the input1.txt file (which is tsv format actually) is your observations, where in rows you have your variables and in columns - your conditions. So, at this point of time you don't have network structure, you rather have observational data, and after launching bnfinder on your data you will get network in SIF format.

So, please, give me an example of what you want to pass as input file, so I can answer your question more clearly.

**Comment by sonujose123** [comment]
Thank you for the quick response. I would like to give "ASIA" data as an
example. It will be great if you could help with this data.

**Comment by alnf** [comment]
So, can you please provide me with the link. Unfortunately, I'm not familiar with ASIA data.

**Comment by alnf** [comment]
Is it from bnlearn R package? If yes, then you should:

1. Transpose the matrix, so you will have variables as rows and observations as columns.
2. Convert yes to 1, and no to 0.
3. Save matrix as tab separated file (you can give any file name extension)
4. Add the mandatory config line at the beginning. For example "#regulators A S", which would mean that visit to Asia and smoking are the main regulatory factors, i.e. nodes with outgoing edges.
5. Check if the file looks similar to input1.txt in terms of format.

Again, for inferring static networks with BNFiner you will have to ensure the acyclicity of the graph by providing regulatory nodes. For dynamic networks inferring (which means your data have to be of a time-series nature) read the doc link I posted above. We use "regulators" term here, because the primary application of BNFinder is biological networks inference, where regulators are genes/proteins, which regulate other genes/proteins.

**Comment by sonujose123** [comment]
Yes. It is.

I have attached the ASIA file for your kind reference.

I have attached asia.bif too.

Thank you!

**Comment by alnf** [comment]
I don't see attached files, but I checked the ASIA data in R, so you may try to follow my instructions.

**Comment by sonujose123** [comment]
Ok. Thank you.

**Comment by alnf** [comment]
If you're writing replies by answering via email, then probably you cannot attach files (not sure, only tried web attachment): https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

**Comment by sonujose123** [comment]
[asia.bif.gz](https://github.com/sysbio-vo/bnfinder/files/632596/asia.bif.gz)
[ASIA.xlsx](https://github.com/sysbio-vo/bnfinder/files/632597/ASIA.xlsx)

**Comment by alnf** [comment]
Have you succeeded in testing ASIA data with BNFinder? May I close the issue?

**Comment by sonujose123** [comment]
Yes please.

**Comment by alnf** [comment]
Thanks, feel free to create more issues in case of troubles:)
